/* auto-generated by tools/build-analysis.js — do not edit */
window.QE_ANALYSIS = {"s7-hematologie-oncologie":["hemato-onco_QE_haute-frequence_by_claude.docx","hemato-onco_QE_haute-frequence_by_claude.pdf"],"s7-neuro-neurochir":["Neuro_Neurochir_QE_by_claude.ai.docx","Neuro_Neurochir_QE_by_claude.ai.pdf"],"s8-anapath-2":["v4-anapath_qe.docx","v4-anapath_qe.pdf"]};
