#!/usr/bin/env node
/**
 * Bake every data/<sem>/<module>.txt into data/<slug>.data.js so the site
 * works fully offline (open index.html / modules/*.html via file://).
 *
 * Usage:  node tools/build-data.js
 *
 * Re-run whenever a .txt file changes or the parser in assets/app.js is
 * updated.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');

function loadParser() {
  const code = fs.readFileSync(path.join(ROOT, 'assets', 'app.js'), 'utf8');
  const m = code.match(/function parseQuestionsFile\(text\) \{[\s\S]*?\n  \}\n/);
  if (!m) throw new Error('parseQuestionsFile not found in assets/app.js');
  return new Function(m[0] + '\nreturn parseQuestionsFile;')();
}

function loadModules() {
  const code = fs.readFileSync(path.join(ROOT, 'assets', 'modules.js'), 'utf8');
  const sandbox = { window: {} };
  new Function('window', code)(sandbox.window);
  return sandbox.window.QE_MODULES || [];
}

// Build a compact qIdx → topic index for the dashboard's Weakness Analysis.
// Each module gets { t: [unique topic strings], q: [topic index per question] }.
function buildTopicIndex(parsed) {
  const tMap = new Map();
  const q = parsed.questions.map(qq => {
    const topic = (qq.topic || '').trim() || '(sans thème)';
    if (!tMap.has(topic)) tMap.set(topic, tMap.size);
    return tMap.get(topic);
  });
  return { t: Array.from(tMap.keys()), q };
}

function main() {
  const parse = loadParser();
  const modules = loadModules();
  const counts = {};
  const topics = {};
  let totalQ = 0, totalBytes = 0;
  for (const m of modules) {
    const srcPath = path.join(ROOT, m.file);
    if (!fs.existsSync(srcPath)) {
      console.warn(`! missing ${m.file}`);
      continue;
    }
    const txt = fs.readFileSync(srcPath, 'utf8');
    const parsed = parse(txt);
    const payload = { slug: m.slug, name: m.name, sem: m.sem, source: m.file, ...parsed };
    const js = `/* auto-generated by tools/build-data.js — do not edit */\nwindow.QE_DATA = ${JSON.stringify(payload)};\n`;
    const outPath = path.join(ROOT, 'data', m.slug + '.data.js');
    fs.writeFileSync(outPath, js);
    counts[m.slug] = { questions: parsed.questions.length, exams: parsed.exams.length };
    topics[m.slug] = buildTopicIndex(parsed);
    totalQ += parsed.questions.length;
    totalBytes += Buffer.byteLength(js, 'utf8');
    console.log(`✓ ${m.slug.padEnd(36)} ${String(parsed.questions.length).padStart(4)} Q  ${(Buffer.byteLength(js, 'utf8') / 1024).toFixed(1).padStart(7)} KB`);
  }
  const countsJs = `/* auto-generated by tools/build-data.js — do not edit */\nwindow.QE_COUNTS = ${JSON.stringify(counts)};\n`;
  fs.writeFileSync(path.join(ROOT, 'data', '_counts.js'), countsJs);
  const topicsJs = `/* auto-generated by tools/build-data.js — do not edit */\nwindow.QE_TOPICS = ${JSON.stringify(topics)};\n`;
  fs.writeFileSync(path.join(ROOT, 'data', '_topics.js'), topicsJs);
  console.log(`\nDone — ${modules.length} modules · ${totalQ} questions · ${(totalBytes / 1024 / 1024).toFixed(2)} MB total`);
  console.log(`Wrote data/_counts.js (${Buffer.byteLength(countsJs, 'utf8')} bytes)`);
  console.log(`Wrote data/_topics.js (${(Buffer.byteLength(topicsJs, 'utf8') / 1024).toFixed(1)} KB)`);
}

main();
